version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: school-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=school_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-school:
    depends_on:
      - mysqldb
    image: yassinealj/school:1.0.0
    container_name: school-app
    restart: on-failure
    ports:
      - "8082:8080"   # ← port externe 8081 pour éviter conflit Jenkins
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/school_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
